# Generated by Django 6.0.4 on 2026-04-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="description",
        ),
    ]
